# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3453bbfdb0a316ef83af1bb48d92fcf6"
name = "fpj-app"
handle = "fpj-app"
application_url = "https://terminology-seminar-va-enjoyed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-46459454.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://terminology-seminar-va-enjoyed.trycloudflare.com/auth/callback",
  "https://terminology-seminar-va-enjoyed.trycloudflare.com/auth/shopify/callback",
  "https://terminology-seminar-va-enjoyed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
